msm8974-common: prop: Allow ro.product.* being set
 * This is mandatory for oreo build script.
 * If not present fail with:
       ERROR: couldn't find ro.product.device in build.prop

Change-Id: Ia3c8a628a236cbc5a7cc812885dfd2077b5494f3